//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProverkaOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class Изделие
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Изделие()
        {
            this.Заказ = new HashSet<Заказ>();
            this.Спецификация_полуфабрикаты1 = new HashSet<Спецификация_полуфабрикаты>();
        }
    
        public string Наименование { get; set; }
        public string Размеры { get; set; }
    
        public virtual Cпецификация_ингредиенты Cпецификация_ингредиенты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказ> Заказ { get; set; }
        public virtual Спецификация_операции Спецификация_операции { get; set; }
        public virtual Спецификация_полуфабрикаты Спецификация_полуфабрикаты { get; set; }
        public virtual Спецификая_украшения_для_торта Спецификая_украшения_для_торта { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Спецификация_полуфабрикаты> Спецификация_полуфабрикаты1 { get; set; }
    }
}
