//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProverkaOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ингредиент
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ингредиент()
        {
            this.Cпецификация_ингредиенты = new HashSet<Cпецификация_ингредиенты>();
        }
    
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public string Единица_размера { get; set; }
        public int Количество { get; set; }
        public string Основной_поставщик { get; set; }
        public byte[] Изображение { get; set; }
        public string Тип_ингредиента { get; set; }
        public decimal Закупочная_цена { get; set; }
        public string ГОСТ { get; set; }
        public string Фасовка { get; set; }
        public string Характеристика { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cпецификация_ингредиенты> Cпецификация_ингредиенты { get; set; }
        public virtual Поставщик Поставщик { get; set; }
    }
}
